name: happy_hour_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_gen_runner: ^5.1.0+1
  flutter_svg: ^1.1.6
  go_router: ^2.2.8
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  get_it: ^7.2.0
  cloud_firestore: ^4.0.4
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
    - family: Icons
      fonts:
        - asset: fonts/Icons.ttf
        
       
     

